### ISSUE TITLE
Mode to continue validating despite failures

### ISSUE THREAD

**Issue by mpickering** [jumattos/lsif-util#11]
I tried to validate a LSIF file that I generated and it was (obviously) incorrect.

However, the failure happened at on the first node and no more of my file was validated.

Given my file works with the LSIF backend I didn't expect such a failure to be critical so it would be good if the validator could keep going past validation failures. 

```
Reading input... done
Verifying vertex 1 of 1152... error
Vertex 1 is not valid:
{
  "language": "haskell",
  "id": 1,
  "type": "vertex",
  "label": "project"
}
ERROR -> requires property "kind"
```

**Comment by jumattos** [comment]
I see this as a fault in my original design. No compiler stops outputting errors after the first one, why should this tool stop?

I am prioritizing this issue. Would a percentage of valid output be useful to you?

**Comment by jumattos** [comment]
A preview of what I've done today:

```
Reading input... done
Verifying vertex 25 of 25... done
Verifying edge 29 of 29... done

Results:
        PASS> vertices emitted before connecting edges
        FAIL> all vertices are used in at least one edge

Vertices:       23 passed, 2 failed, 25 total
Edges:          27 passed, 2 failed, 29 total

edge 33: FAIL> requires properties "inV" and "outV"
{
  "id": 33,
  "type": "edge",
  "label": "textDocument/hover",
  "outV": 26,
  "iV": 32
}

vertex 32: FAIL> not connected to any other vertex
{
  "id": 32,
  "type": "vertex",
  "label": "hoverResult",
  "result": {
    "contents": [
      {
        "language": "typescript",
        "value": "let a: foo"
      }
    ]
  }
}

vertex 13: FAIL> requires property "result";
{
  "id": 13,
  "type": "vertex",
  "label": "definitionResult",
  "ressult": 8
}

vertex 44: FAIL> requires property "start";
{
  "id": 44,
  "type": "vertex",
  "label": "range",
  "staert": {
    "line": 7,
    "character": 0
  },
  "end": {
    "line": 7,
    "character": 1
  },
  "tag": {
    "type": "reference",
    "text": "a"
  }
}

edge 45: FAIL> unknown label
{
  "id": 45,
  "type": "edge",
  "label": "contaains",
  "outV": 3,
  "inV": 44
}
```

This output is much more informative. Thank you for your feedback!

**Comment by jumattos** [comment]
Before I push these changes, I want to think about a summary version for when the `verbose` flag is off.

**Comment by mpickering** [comment]
Thanks @jumattos looks perfect.

**Comment by jumattos** [comment]
I pushed these changes half an hour ago, so I will close this issue for now. Thanks again for the feedback @mpickering! Let me know if you have any trouble running the new version of the tool.
