### ISSUE TITLE
Validation failure does not match specification

### ISSUE THREAD

**Issue by mpickering** [jumattos/lsif-util#12]
Attempting to validate a `lsif.json` file that I generated, the error is:

```
Reading input... done
Verifying vertex 1 of 1152... error
Vertex 1 is not valid:
{
  "language": "haskell",
  "id": 1,
  "type": "vertex",
  "label": "project"
}
ERROR -> requires property "kind"
```

But consulting the specification for the [project vertex](https://github.com/Microsoft/language-server-protocol/blob/master/indexFormat/specification.md#the-project-vertex) does not indicate that the project vertex should have a property called "kind" so I don't know why validation fails.

**Comment by arjunattam** [comment]
Thanks for pointing this out @mpickering. It seems we have an issue in the spec, where the `project` vertex lacks the `kind` property. This particular util is using the updated [protocol definition](https://github.com/Microsoft/lsif-typescript/blob/dbaeumer/newStructure/protocol/src/protocol.ts#L286). We've gone through some recent changes but the spec hasn't kept up – apologies for the confusion, and I'll fix this in the spec.

**Comment by jumattos** [comment]
Hey @arjun27, would you mind closing this issue once you update the spec? Thanks!

**Comment by arjunattam** [comment]
Sure, filed this https://github.com/Microsoft/language-server-protocol/pull/710

**Comment by arjunattam** [comment]
The change has been merged, and we can close this issue now
