### ISSUE TITLE
Add support for `line` output format

### ISSUE THREAD

**Issue by arjunattam** [jumattos/lsif-util#16]
The `lsif-tsc` tool inside [lsif-node](https://github.com/Microsoft/lsif-node) has two different output formats:

1. `json`: which generates one large json array, with vertices and edges as array elements
2. `line`: which outputs one json element (vertex or edge) in one line (not a json array as a whole)

The `line` is the default output format (unless overriden with `--outputFormat json`), and it would be useful to support in the validation tool.

**Comment by jumattos** [comment]
Clarification question: you mean adding support for a different kind of input (in this case, the line format)?

For a moment I thought this issue was about the output that the tool generates, but I believe it's about the input file.

**Comment by arjunattam** [comment]
That’s correct, this is about supporting the line format in the input file.

**Comment by jumattos** [comment]
This is just something that I overlooked, but it shouldn't be hard to implement.

Should we keep the `json` format as our default or switch to the line format? I personally think we should mimic the default for the LSIF output tools, but I am not sure if they agree with each other (typescript lsif is line).

**Comment by arjunattam** [comment]
I agree we should mimic the defaults for the LSIF output tools, and we will need clear docs and error messages to handholding users that might be expecting otherwise.

**Comment by jumattos** [comment]
Do you happen to know what this default is? A common default between the multiple LSIF tools?

**Comment by arjunattam** [comment]
The typescript tooling uses line by line as a default, which is also what the build task expects—since line format suits streaming better. We have a mix in other tools right now, and I'm working on making it the recommended default in the spec.

**Comment by jumattos** [comment]
Well, if you're working on making it the default, then I might as well change the default of this tool. It makes total sense for streaming, you're right.

I've been meaning to rewrite the project to reuse some code that all of the tools need (e.g. read input). I will change the default along with that.

**Comment by jumattos** [comment]
Fixed at #18
