### ISSUE TITLE
Ignore content for verbose graphs

### ISSUE THREAD

**Issue by arjunattam** [jumattos/lsif-util#6]
When a graph is generated with the `-v` option on an LSIF output that embeds the file contents, this error is thrown:

```
Error: <stdin>: syntax error in line 20 scanning a quoted string (missing endquote? longer than 16384?)
String starting:"[901] document
uri = "file:///Users/arjun/lsif-typescript/tsc-lsif/node_modules/
```

I think the `-v` option should ignore the `contents` key on `document` vertices, since fitting that into a graph will be difficult. Currently, there is no way to generate a verbose graph on an LSIF that embeds document contents

**Comment by jumattos** [comment]
Thanks for bringing this to my attention, I didn't know about it. I will add this to the backlog. 👍

**Comment by jumattos** [comment]
Hey! Just letting you know I have addressed this issue on my latest commit to the UI updates that are coming soon: https://github.com/jumattos/lsif-util/commit/1682785cac68c4d043fb5f69625f6ffb33d569f9
